const data = [
  {
    id: 1,
    courseName: "Mastering Python for Beginners",
    aboutCourse:
      "Learn the fundamentals of Python programming and build a strong foundation in data science and machine learning.",
    duration: "4 weeks",
    price: 12000,
    language: "Python",
    framework: 'null',
    level: "Beginner",
    category: "Programming",
    popularity: "Medium",
  },
  {
    id: 2,
    courseName: "ReactJS: Building Scalable Applications",
    aboutCourse:
      "Learn the art of building fast, scalable, and maintainable applications with ReactJS and its ecosystem.",
    duration: "6 weeks",
    price: 18000,
    language: "JavaScript",
    framework: "ReactJS",
    level: "Intermediate",
    category: "Frontend Development",
    popularity: "Very High",
  },
  {
    id: 3,
    courseName: "Java Fundamentals for Android App Development",
    aboutCourse:
      "Learn the basics of Java programming and build a strong foundation for Android app development.",
    duration: "5 weeks",
    price: 15000,
    language: "Java",
    framework: 'null',
    level: "Beginner",
    category: "Mobile App Development",
    popularity: "Very High",
  },
  {
    id: 4,
    courseName: "Angular: Building Complex Web Applications",
    aboutCourse:
      "Learn the art of building complex web applications with Angular and its powerful ecosystem.",
    duration: "8 weeks",
    price: 25000,
    language: "JavaScript",
    framework: "Angular",
    level: "Advanced",
    category: "Frontend Development",
    popularity: "High",
  },
  {
    id: 5,
    courseName: "Data Science with R Programming",
    aboutCourse:
      "Learn the art of data science and machine learning with R programming and its powerful libraries.",
    duration: "6 weeks",
    price: 20000,
    language: "R",
    framework: 'null',
    level: "Intermediate",
    category: "Data Science",
    popularity: "Medium",
  },
  {
    id: 6,
    courseName: "VueJS: Building Progressive Web Apps",
    aboutCourse:
      "Learn the art of building progressive web apps with VueJS and its ecosystem.",
    duration: "5 weeks",
    price: 18000,
    language: "JavaScript",
    framework: "VueJS",
    level: "Intermediate",
    category: "Frontend Development",
    popularity: "Essential",
  },
  {
    id: 7,
    courseName: "Machine Learning with TensorFlow",
    aboutCourse:
      "Learn the art of machine learning with TensorFlow and its powerful ecosystem.",
    duration: "8 weeks",
    price: 30000,
    language: "Python",
    framework: "TensorFlow",
    level: "Advanced",
    category: "Machine Learning",
    popularity: "Medium",
  },
  {
    id: 8,
    courseName: "Full Stack Development with NodeJS",
    aboutCourse:
      "Learn the art of full stack development with NodeJS and its ecosystem.",
    duration: "10 weeks",
    price: 35000,
    language: "JavaScript",
    framework: "NodeJS",
    level: "Advanced",
    category: "Full Stack Development",
    popularity: "High",
  },
  {
    id: 9,
    courseName: "C++ Programming for Game Development",
    aboutCourse:
      "Learn the fundamentals of C++ programming and build a strong foundation for game development.",
    duration: "6 weeks",
    price: 22000,
    language: "C++",
    framework: 'null',
    level: "Intermediate",
    category: "Game Development",
    popularity: "Very High",
  },
  {
    id: 10,
    courseName: "Ruby on Rails: Building Web Applications",
    aboutCourse:
      "Learn the art of building web applications with Ruby on Rails and its ecosystem.",
    duration: "8 weeks",
    price: 28000,
    language: "Ruby",
    framework: "Ruby on Rails",
    level: "Intermediate",
    category: "Backend Development",
    popularity: "Medium",
  },
  {
    id: 11,
    courseName: "Python for Data Science",
    aboutCourse:
      "Master the fundamentals of Python for data manipulation, analysis, and visualization.",
    duration: "8 weeks",
    price: 18000,
    language: "Python",
    framework: "Numpy, Pandas, Matplotlib",
    level: "Intermediate",
    category: "Data Science",
    popularity: "High",
  },
  {
    id: 12,
    courseName: "MERN Stack Development",
    aboutCourse:
      "Learn the MERN stack (MongoDB, Express.js, React, Node.js) to build full-fledged web applications.",
    duration: "12 weeks",
    price: 28000,
    language: "JavaScript",
    framework: "MERN Stack",
    level: "Advanced",
    category: "Web Development",
    popularity: "High",
  },
  {
    id: 13,
    courseName: "Git and GitHub for Version Control",
    aboutCourse:
      "Master Git and GitHub to manage your code versions effectively and collaborate with others.",
    duration: "3 weeks",
    price: 8000,
    language: "N/A", 
    framework: "Git, GitHub",
    level: "Beginner",
    category: "Development Tools",
    popularity: "Essential",
  },
];

export default data;
